# Generated by Django 4.1.2 on 2023-03-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='UserRegister',
        ),
    ]
