# Generated by Django 4.1.2 on 2023-03-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_register_userregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='Image',
            field=models.ImageField(default=None, upload_to='User/'),
        ),
    ]
