# Generated by Django 4.1.2 on 2023-03-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userregister_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='Image',
            field=models.ImageField(default=None, upload_to='media/User/'),
        ),
    ]
