# Generated by Django 4.1.2 on 2023-03-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userregister_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=25)),
                ('Date', models.DateField()),
                ('TransactionAmount', models.FloatField(default=0)),
                ('TotalAmount', models.FloatField(default=0)),
                ('Action', models.CharField(max_length=25)),
            ],
        ),
    ]
