# Generated by Django 4.1.2 on 2023-03-19 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='Notifications',
            field=models.TextField(default=datetime.datetime(2023, 3, 19, 12, 40, 5, 468045, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
